name: CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 构建 Docker 镜像
        run: docker build -t cicd-demo:latest .

      - name: 查看镜像
        run: docker images
